defaults:
  - controlled_audio_benchmark_schema
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null
